instance_create_depth(x, y, 0, background_music)
instance_create_depth(x, y, 0, draw_static_hud)
instance_create_depth(x, y, 0, draw_remaining_time)
instance_create_depth(x, y, 0, draw_total_coins)
instance_create_depth(x, y, 0, draw_total_score)
instance_create_depth(x, y, 0, pause_game)